language: node_js
node_js:
  - 12
stages:
  - name: deploy
    if: branch = master
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  script: bash scripts/deploy.sh
